from enum import Enum


class NextAction(str, Enum):

    START_ONBOARDING = "START_ONBOARDING"

    ENTER_NAME = "ENTER_NAME"

    ENTER_PHONE_NUMBER = "ENTER_PHONE_NUMBER"

    COMPLETE = "COMPLETE"

    SHOW_MAIN_MENU = "SHOW_MAIN_MENU"